
idx_bt1: /scratch/genomic_med/apps/annot/indexes/bowtie/hg19
macs_g: hs
macs_pvalue: 10e-5
macs2_g: hs
macs2_pvalue: 10e-5
macs2_pvalue_broad: 10e-5

#superEnhancer genome
rose_g: hg19

#number of reads downsample to
target_reads: 15000000


# Path to a JSON file with samples and their corresponding FASTQ files.
SAMPLES: './SRR.txt'

CLUSTER_JSON: './cluster.json'
