title: "Full-chipseq MultiQC report"
report_comment: "Generated on DATE for project PROJECTNAME"


report_header_info:
    - Contact E-mail: 'adrien.foucal@gmail.com'
    - Pipeline Type: 'ChIP-seq'


module_order:
    - MACS2_broadPeak_count
    - MACS2_narrowPeak_count
    - featureCounts:
        name: 'FRiP'
        info: 'Fraction of reads in peaks (FRiP)'
    - deepTools
    - bowtie2
    - fastqc



section_comments:
    read_distribution_profile_plot: 'Accumulated view of the distribution of sequence reads around TSS.'

custom_data:
    encode_metrics:
        plot_type: 'generalstats'
        file_format: 'tsv'
        pconfig:
            - NRF:
                namespace: "NRF"
                title: "NRF"
                description: "ratio between the number of positions in the genome that uniquely mapped reads map to and the total number of uniquely mappable reads"
                max: 1
                min: 0
                scale: 'RdYlGn'
            - PBC1:
                namespace: "PBC1"
                title: "PBC1"
                description: "ratio of genomic locations with EXACTLY one read pair over the genomic locations with AT LEAST one read pair"
                max: 1
                min: 0
                scale: 'RdYlGn'
            - PBC2:
                namespace: "PBC2"
                title: "PBC2"
                description: "ratio of genomic locations with EXACTLY one read pair over the genomic locations with EXACTLY two read pairs"
                max: 10
                min: 0
                scale: 'RdYlGn'


sp:
    encode_metrics:
        fn: '*encodeQC.txt'
