title: "Full-chipseq pipeline"
intro_text: ""
report_comment: "Generated on DATE for project PROJECTNAME"


report_header_info:
    - Contact E-mail: 'adrien.foucal@gmail.com'
    - Pipeline Type: 'ChIP-seq'

module_order:
    - tss_plot
    - featureCounts:
        namespace: 'FRiP'
        name: 'FRiP'
        title: 'FRiP'
        info: 'Fraction of reads in peaks (FRiP)'
    - MACS2_broadPeak_count
    - MACS2_narrowPeak_count
    - SEACR_relaxed_count
    - SEACR_stringent_count
    - picard:
        name: "Insert Size"
        target: "Picard"
        info: 'Insert size calculated by Picard CollectMultipleMetrics'
    - deeptools:
        name: "Sample correlation heatmap"
        target: "deepTools"
        info: "Pearson correlation coefficient for each sample"
    - preseq:
        name: 'Complexity curve'
        target: 'Preseq'
    - samblaster:
        name: 'Duplicate count'
        target: 'Samblaster'
    - bowtie2:
        name: 'Alignment metrics'
    - samtools:
        name: 'Samtools Stats (raw)'
        info: 'Raw read counts'
        anchor: 'read_counts_raw'
        path_filters:
            - '*.raw.bam.stats'  
    - samtools:
        name: 'Samtools Stats (filtered)'
        info: 'Read counts after filtering for properly aligned reads and MQ passed'
        anchor: 'Read_counts_filtered'
        target: ''
        path_filters:
            - '*.sorted.bam.stats'
    - fastqc

table_columns_visible:
    FRiP:
        Assigned: False
    phantompeakqualtools:
        Estimated_Fragment_Length_bp: False
    FastQC: False
    FastQC (raw): False
    Samtools Stats (raw): False
    Samtools Stats (filtered):
        raw_total_sequences: True
        non-primary_alignments: False
        reads_mapped: False
        reads_mapped_percent: False
        reads_properly_paired_percent: False
        reads_MQ0_percent: False
        error_rate: False

section_comments:
    deeptools_correlation: "Correlation from deepTools plotCorrelation based on read counts from multiBigwigSummary"

custom_data:
    encode_metrics:
        plot_type: 'generalstats'
        file_format: 'tsv'
        pconfig:
            - NRF:
                namespace: "NRF"
                title: "NRF"
                description: "ratio between the number of positions in the genome that uniquely mapped reads map to and the total number of uniquely mappable reads"
                max: 1
                min: 0
                scale: 'RdYlGn'
            - PBC1:
                namespace: "PBC1"
                title: "PBC1"
                description: "ratio of genomic locations with EXACTLY one read pair over the genomic locations with AT LEAST one read pair"
                max: 1
                min: 0
                scale: 'RdYlGn'
            - PBC2:
                namespace: "PBC2"
                title: "PBC2"
                description: "ratio of genomic locations with EXACTLY one read pair over the genomic locations with EXACTLY two read pairs"
                max: 10
                min: 0
                scale: 'RdYlGn'
    tss_stat:
        plot_type: 'generalstats'
        file_format: 'tsv'
        pconfig:
            - TSS:
                namespace: "TSS Enrichment"
                title: "TSS Enrichment"
                description: "Signal to noise calculation around TSS"
                max: 10
                min: 0
                scale: 'RdYlGn'
    tss_plot:
        file_format: 'tsv'
        section_name: 'TSS Coverage'
        description: 'The transcription start site profile plot (TSS) displays the number of reads that map around the transcription start site of selected genes'
        plot_type: 'linegraph'
        pconfig:
            id: 'tss_plot'
            title: 'TSS plot'
            ylab: 'Average read coverage (per million mapped reads)'
            ymax: 30
            ymin: 0


table_cond_formatting_rules:
    mqc-generalstats-tss_enrichment-TSS:
        pass:
            - gt: 10
        warn:
            - lt: 10
        fail:
            - lt: 6
    mqc-generalstats-pbc1-PBC1:
        pass:
            - gt: 0.9
        warn:
            - lt: 0.9
        fail:
            - lt: 0.7
    mqc-generalstats-pbc2-PBC2:
        pass:
            - gt: 3
        warn:
            - lt: 3
        fail:
            - lt: 1
    mqc-generalstats-nrf-NRF:
        pass:
            - gt: 0.9
        warn:
            - lt: 0.9
        fail:
            - lt: 0.7

sp:
    encode_metrics:
        fn: '*encodeQC.txt'
    tss_stat:
        fn: '*max.txt'
    tss_plot:
        fn: '*tss.txt'

extra_fn_clean_exts:
  - ".raw"

